package pojo;
// Generated Oct 12, 2021 7:53:16 PM by Hibernate Tools 4.3.1

import DAO.DAOLogin;
import java.util.List;
import javax.faces.bean.ManagedBean;

/**
 * Admin generated by hbm2java
 */

@ManagedBean
public class Admin  implements java.io.Serializable {


     private Integer idAdmin;
     private String username;
     private String password;
     
     public String login_admin(){
         DAOLogin uDao = new DAOLogin();
         List<Admin> tu = uDao.getByAdmin(username, password);
         
         try{
             if(tu != null){
             username = tu.get(0).username;
             password = tu.get(0).password;
             return "edit_produk";
            }
         }
         catch (Exception e){ 
             System.out.println(e);
         }
         
         return "gagal_login";
     } 
     
    public Admin() {
    }

    public Admin(String username, String password) {
       this.username = username;
       this.password = password;
    }
   
    public Integer getIdAdmin() {
        return this.idAdmin;
    }
    
    public void setIdAdmin(Integer idAdmin) {
        this.idAdmin = idAdmin;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


