package pojo;
// Generated Oct 12, 2021 7:53:16 PM by Hibernate Tools 4.3.1

import DAO.DAOLogin;
import DAO.DAOUser;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;

/**
 * User generated by hbm2java
 */
@ManagedBean
public class User  implements java.io.Serializable {


     private Integer idUser;
     private String username;
     private String password;
     private String jenisKelamin;
     private String noTelp;
     private String alamat;
     
     public void save_user(){
         DAOLogin add = new DAOLogin();
         add.add_user(this);
     }
     
     public String login_user(){
         DAOLogin uDao = new DAOLogin();
         List<User> tu = uDao.getBy(username, password);
         
         try{
             if(tu != null){
             username = tu.get(0).username;
             password = tu.get(0).password;
             return "index";
            }
         }
         catch (Exception e){ 
             System.out.println(e);
         }
         
         return "gagal_login";
     }
     
     public List<User> getAllRecords(){
         DAOUser usr = new DAOUser();
         List<User> lUsr = usr.retrveUser();
         return lUsr;
     }
     
     public String getById(){
         String id_user = idUser.toString();
         DAOUser usr = new DAOUser();
         List<User> lUsr = usr.getbyId(id_user);
         
         username = lUsr.get(0).username;
         password = lUsr.get(0).password;
         jenisKelamin = lUsr.get(0).jenisKelamin;
         noTelp = lUsr.get(0).noTelp;
         alamat = lUsr.get(0).alamat;
         
         return "edit_produk";
     }
     
     public void Edit(){
         DAOUser usr = new DAOUser();
         usr.editUser(this);
         
         username = "";
         password = "";
         jenisKelamin = "";
         noTelp = "";
         alamat = "";
         
         FacesMessage facesMessage = new FacesMessage(FacesMessage.SEVERITY_INFO, "Berhasil melakukan update", null);
     }

    public User() {
    }

    public User(String username, String password, String jenisKelamin, String noTelp, String alamat) {
       this.username = username;
       this.password = password;
       this.jenisKelamin = jenisKelamin;
       this.noTelp = noTelp;
       this.alamat = alamat;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getJenisKelamin() {
        return this.jenisKelamin;
    }
    
    public void setJenisKelamin(String jenisKelamin) {
        this.jenisKelamin = jenisKelamin;
    }
    public String getNoTelp() {
        return this.noTelp;
    }
    
    public void setNoTelp(String noTelp) {
        this.noTelp = noTelp;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }




}


